# Generated by Django 3.0.2 on 2020-01-08 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='description',
            field=models.CharField(help_text='Enter the description', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='image',
            field=models.CharField(help_text='Enter the image url', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.CharField(help_text='Enter the description', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.CharField(help_text='Enter the image url', max_length=200, null=True),
        ),
    ]
